import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { AuthContextProvider } from "@/context/AuthContext";

/**
 * Geist Sans font configuration
 * Loads the Geist Sans font family and makes it available via CSS variable.
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * Geist Mono font configuration
 * Loads the Geist Mono font family and makes it available via CSS variable.
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Application metadata
 * Used for SEO and browser tab display.
 * TODO: Update with actual application title and description
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root Layout Component
 * 
 * The root layout wrapper for the entire application.
 * Provides:
 * - Font configuration (Geist Sans & Mono)
 * - Global CSS styles
 * - Authentication context to all child components
 * - Common layout structure (Header, main content, Footer)
 * 
 * This layout wraps all pages in the application.
 * 
 * @param children - Child page components to render
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen min-w-screen flex flex-col">
        {/* Wrap entire app in AuthContextProvider to enable auth throughout */}
        <AuthContextProvider>
          <Header />
          <main className="flex flex-col flex-1">{children}</main>
          <Footer />
        </AuthContextProvider>
      </body>
    </html>
  );
}
